# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ndvi <- function(red, nir) {
    .Call(`_spectral_ndvi`, red, nir)
}

.evi2 <- function(red, nir) {
    .Call(`_spectral_evi2`, red, nir)
}

.ndwi2 <- function(green, nir) {
    .Call(`_spectral_ndwi2`, green, nir)
}

.bndvi <- function(blue, nir) {
    .Call(`_spectral_bndvi`, blue, nir)
}

