# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ndvi_op <- function(red, nir) {
    .Call(`_spectral_ndvi_op`, red, nir)
}

evi2_op <- function(red, nir) {
    .Call(`_spectral_evi2_op`, red, nir)
}

ndwi2_op <- function(green, nir) {
    .Call(`_spectral_ndwi2_op`, green, nir)
}

bndvi_op <- function(blue, nir) {
    .Call(`_spectral_bndvi_op`, blue, nir)
}

